/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/AudioManager")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class AudioManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "eb16f2ee53160bd418c52ebab1b1f378";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.AudioClip m_soundFoundPlayer = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_soundFoundPlayer),
            };
        }
    }
}

#endif
