/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DetectingCollisions")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class DetectingCollisions : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "4f5cdf23b9fe9de40877718005b0d1d0";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_vfxFoundPlayer = default;
        [SerializeField] public UnityEngine.GameObject m_ghostFoundFirstPlayer = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_vfxFoundPlayer),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_ghostFoundFirstPlayer),
            };
        }
    }
}

#endif
