/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/FireflyLightColor")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class FireflyLightColor : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "9719d1af57e32874ba4920b01f67f54a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Material m_blue = default;
        [SerializeField] public UnityEngine.Material m_yellow = default;
        [SerializeField] public UnityEngine.Material m_red = default;
        [SerializeField] public System.Double m_colorIndex = 0;
        [SerializeField] public System.Double m_distanceToYellow = 2;
        [SerializeField] public System.Double m_distanceToRed = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_blue),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_yellow),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_red),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_colorIndex),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_distanceToYellow),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_distanceToRed),
            };
        }
    }
}

#endif
