/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ManagerGame")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class ManagerGame : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "aa92ea622b7f1cc4ab1d8c162a6abd8c";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_playerPet = default;
        [SerializeField] public UnityEngine.GameObject m_fireFlyLightColor01 = default;
        [SerializeField] public UnityEngine.GameObject m_fireFlyLightColor02 = default;
        [SerializeField] public UnityEngine.GameObject m_pointRespawnLobby = default;
        [SerializeField] public UnityEngine.GameObject m_pointRespawnPlayerSeeker = default;
        [SerializeField] public UnityEngine.GameObject m_pointRespawnPlayerHider01 = default;
        [SerializeField] public UnityEngine.GameObject m_pointRespawnPlayerHider02 = default;
        [SerializeField] public UnityEngine.GameObject m_pointRespawnPlayerHider03 = default;
        [SerializeField] public UnityEngine.GameObject m_pointRespawnPlayerHider04 = default;
        [SerializeField] public UnityEngine.GameObject m_objsHides01 = default;
        [SerializeField] public UnityEngine.GameObject m_objsHides02 = default;
        [SerializeField] public UnityEngine.GameObject m_objsHides0304 = default;
        [SerializeField] public UnityEngine.GameObject m_roadPedestal01 = default;
        [SerializeField] public UnityEngine.GameObject m_roadPedestal02 = default;
        [SerializeField] public UnityEngine.GameObject m_roadPedestal03 = default;
        [SerializeField] public UnityEngine.GameObject m_roadPedestal04 = default;
        [SerializeField] public UnityEngine.GameObject m_custome01 = default;
        [SerializeField] public UnityEngine.GameObject m_custome02 = default;
        [SerializeField] public UnityEngine.GameObject m_custome03 = default;
        [SerializeField] public UnityEngine.GameObject m_custome04 = default;
        [SerializeField] public UnityEngine.GameObject m_custome05 = default;
        [SerializeField] public UnityEngine.GameObject m_custome06 = default;
        [SerializeField] public Highrise.Client.TapHandler m_btnObjHide01Point01 = default;
        [SerializeField] public Highrise.Client.TapHandler m_btnObjHide02Point01 = default;
        [SerializeField] public Highrise.Client.TapHandler m_btnObjHide03Point01 = default;
        [SerializeField] public Highrise.Client.TapHandler m_btnObjHide01Point02 = default;
        [SerializeField] public Highrise.Client.TapHandler m_btnObjHide02Point02 = default;
        [SerializeField] public Highrise.Client.TapHandler m_btnObjHide03Point02 = default;
        [SerializeField] public Highrise.Client.TapHandler m_btnObjHide01Point0304 = default;
        [SerializeField] public Highrise.Client.TapHandler m_btnObjHide02Point0304 = default;
        [SerializeField] public Highrise.Client.TapHandler m_btnObjHide03Point0304 = default;
        [SerializeField] public UnityEngine.GameObject m_navMeshAgentWithoutHiders = default;
        [SerializeField] public UnityEngine.GameObject m_navMeshAgentWithHiders = default;
        [SerializeField] public UnityEngine.GameObject m_navMeshLobby = default;
        [SerializeField] public UnityEngine.GameObject m_lobbyRoom = default;
        [SerializeField] public UnityEngine.GameObject m_worldRoom = default;
        [SerializeField] public UnityEngine.GameObject m_doorSeeker = default;
        [SerializeField] public UnityEngine.GameObject m_UIManager = default;
        [SerializeField] public UnityEngine.GameObject m_CameraManager = default;
        [SerializeField] public UnityEngine.GameObject m_zoneGreen = default;
        [SerializeField] public UnityEngine.GameObject m_zoneOrange = default;
        [SerializeField] public UnityEngine.GameObject m_doorsClosedZoneGreen = default;
        [SerializeField] public UnityEngine.GameObject m_doorsOpenZoneGreen = default;
        [SerializeField] public UnityEngine.GameObject m_doorsClosedZoneOrange = default;
        [SerializeField] public UnityEngine.GameObject m_doorsOpenZoneOrange = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_playerPet),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_fireFlyLightColor01),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_fireFlyLightColor02),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_pointRespawnLobby),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_pointRespawnPlayerSeeker),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_pointRespawnPlayerHider01),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_pointRespawnPlayerHider02),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_pointRespawnPlayerHider03),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_pointRespawnPlayerHider04),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_objsHides01),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_objsHides02),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_objsHides0304),
                CreateSerializedProperty(_script.GetPropertyAt(12), m_roadPedestal01),
                CreateSerializedProperty(_script.GetPropertyAt(13), m_roadPedestal02),
                CreateSerializedProperty(_script.GetPropertyAt(14), m_roadPedestal03),
                CreateSerializedProperty(_script.GetPropertyAt(15), m_roadPedestal04),
                CreateSerializedProperty(_script.GetPropertyAt(16), m_custome01),
                CreateSerializedProperty(_script.GetPropertyAt(17), m_custome02),
                CreateSerializedProperty(_script.GetPropertyAt(18), m_custome03),
                CreateSerializedProperty(_script.GetPropertyAt(19), m_custome04),
                CreateSerializedProperty(_script.GetPropertyAt(20), m_custome05),
                CreateSerializedProperty(_script.GetPropertyAt(21), m_custome06),
                CreateSerializedProperty(_script.GetPropertyAt(22), m_btnObjHide01Point01),
                CreateSerializedProperty(_script.GetPropertyAt(23), m_btnObjHide02Point01),
                CreateSerializedProperty(_script.GetPropertyAt(24), m_btnObjHide03Point01),
                CreateSerializedProperty(_script.GetPropertyAt(25), m_btnObjHide01Point02),
                CreateSerializedProperty(_script.GetPropertyAt(26), m_btnObjHide02Point02),
                CreateSerializedProperty(_script.GetPropertyAt(27), m_btnObjHide03Point02),
                CreateSerializedProperty(_script.GetPropertyAt(28), m_btnObjHide01Point0304),
                CreateSerializedProperty(_script.GetPropertyAt(29), m_btnObjHide02Point0304),
                CreateSerializedProperty(_script.GetPropertyAt(30), m_btnObjHide03Point0304),
                CreateSerializedProperty(_script.GetPropertyAt(31), m_navMeshAgentWithoutHiders),
                CreateSerializedProperty(_script.GetPropertyAt(32), m_navMeshAgentWithHiders),
                CreateSerializedProperty(_script.GetPropertyAt(33), m_navMeshLobby),
                CreateSerializedProperty(_script.GetPropertyAt(34), m_lobbyRoom),
                CreateSerializedProperty(_script.GetPropertyAt(35), m_worldRoom),
                CreateSerializedProperty(_script.GetPropertyAt(36), m_doorSeeker),
                CreateSerializedProperty(_script.GetPropertyAt(37), m_UIManager),
                CreateSerializedProperty(_script.GetPropertyAt(38), m_CameraManager),
                CreateSerializedProperty(_script.GetPropertyAt(39), m_zoneGreen),
                CreateSerializedProperty(_script.GetPropertyAt(40), m_zoneOrange),
                CreateSerializedProperty(_script.GetPropertyAt(41), m_doorsClosedZoneGreen),
                CreateSerializedProperty(_script.GetPropertyAt(42), m_doorsOpenZoneGreen),
                CreateSerializedProperty(_script.GetPropertyAt(43), m_doorsClosedZoneOrange),
                CreateSerializedProperty(_script.GetPropertyAt(44), m_doorsOpenZoneOrange),
            };
        }
    }
}

#endif
