/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/MechanicsLobby")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class MechanicsLobby : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "2a7248960d0af7c48a4fb1b8a3e6f2e3";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_ghostCustome01 = default;
        [SerializeField] public UnityEngine.GameObject m_ghostCustome02 = default;
        [SerializeField] public UnityEngine.GameObject m_ghostCustome03 = default;
        [SerializeField] public Highrise.Client.TapHandler m_pedestalCustome01Lobby_btn01 = default;
        [SerializeField] public Highrise.Client.TapHandler m_pedestalCustome01Lobby_btn02 = default;
        [SerializeField] public Highrise.Client.TapHandler m_pedestalCustome01Lobby_btn03 = default;
        [SerializeField] public Highrise.Client.TapHandler m_pedestalCustome02Lobby_btn01 = default;
        [SerializeField] public Highrise.Client.TapHandler m_pedestalCustome02Lobby_btn02 = default;
        [SerializeField] public Highrise.Client.TapHandler m_pedestalCustome02Lobby_btn03 = default;
        [SerializeField] public Highrise.Client.TapHandler m_pedestalCustome03Lobby_btn01 = default;
        [SerializeField] public Highrise.Client.TapHandler m_pedestalCustome03Lobby_btn02 = default;
        [SerializeField] public Highrise.Client.TapHandler m_pedestalCustome03Lobby_btn03 = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_ghostCustome01),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_ghostCustome02),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_ghostCustome03),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_pedestalCustome01Lobby_btn01),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_pedestalCustome01Lobby_btn02),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_pedestalCustome01Lobby_btn03),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_pedestalCustome02Lobby_btn01),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_pedestalCustome02Lobby_btn02),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_pedestalCustome02Lobby_btn03),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_pedestalCustome03Lobby_btn01),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_pedestalCustome03Lobby_btn02),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_pedestalCustome03Lobby_btn03),
            };
        }
    }
}

#endif
