/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PlayersToLobby")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class PlayersToLobby : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "75abf87b497b1a24dbd484b8041a5494";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_minNumPlayers = 3;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_minNumPlayers),
            };
        }
    }
}

#endif
